version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"

    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"

    labels:
      - "docker"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"

    labels:
      - "docker"