sonar.projectKey=juppsy_devops-zero-to-production
sonar.organization=juppsy

sonar.projectName=devops-zero-to-production
sonar.projectVersion=1.0

sonar.sources=app,scripts

sonar.sourceEncoding=UTF-8