trigger:
  - main

variables:
  APP_NAME: devops-zero-to-production
  ENVIRONMENT: development

stages:
  - stage: Validate
    displayName: "Validate"

    jobs: 
      - job: Validate
        displayName: "Validate Project"

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            displayName: "Checkout repository"

          - script: ./scripts/validate-project.sh
            displayName: "Validate project"

          - script: |
              echo "===== BUILD ENVIRONMENT ====="

              echo ""
              echo "Application: $(APP_NAME)"

              echo "Environment: $(ENVIRONMENT)"

              echo ""
              echo "Current directory:"
              pwd

              echo ""
              echo "Current user:"
              whoami

              echo ""
              echo "Git version:"
              git --version

              echo ""
              echo "Python version:"
              python3 --version

              echo ""
              echo "Docker version:"
              docker --version

              echo ""
              echo "Repository files:"
              ls -la
            displayName: "Inspect build environment"

          - script: |
              python3 -m pip install --upgrade pip
              pip3 install -r app/requirements.txt
            displayName: "Install Python dependencies"
      
          - script: |
              python -m ruff check .
            displayName: "Run Ruff"

          - script: |
              python -m pytest
            displayName: "Run tests"

          - task: SonarCloudPrepare@4
            inputs:
              SonarQube: 'sonarqube connection'
              organization: 'juppsy'
              scannerMode: 'cli'
              cliScannerVersion: '8.1.0.6389'
              configMode: 'file'
            displayName: "Prepare SonarCloud Analysis"

          - task: SonarCloudAnalyze@4
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
            displayName: "Run SonarCloud Analysis"
          
          - task: SonarCloudPublish@4
            inputs:
              pollingTimeoutSec: "300"
            displayName: "Check Quality Gate"

          - task: SnykSecurityScan@1
            inputs:
              serviceConnectionEndpoint: 'snyk connection'
              testType: 'app'
              targetFile: 'app/requirements.txt'
              monitorWhen: 'always'
              failOnIssues: true

          - script: |
              echo "===== BUILD DOCKER IMAGE ====="

              docker build -f docker/Dockerfile -t demo-app:$(Build.BuildId) .
            displayName: "Build Docker image"

          - script: |
              echo "===== SMOKE TEST DOCKER IMAGE ====="

              docker run -d --name demo-container -p 8080:8080 demo-app:$(Build.BuildId)

              sleep 5

              curl -f http://localhost:8080

              docker stop demo-container
              docker rm demo-container
            displayName: "Smoke test Docker image"